#!/bin/sh

main() {
    files=$(getChangedFiles)
    formatFiles $files
    stageFiles $files
    exit 0
}

getChangedFiles() {
    if git rev-parse --verify HEAD >/dev/null 2>&1
    then
	      against=HEAD
    else
	      # Initial commit: diff against an empty tree object
	      against=$(git hash-object -t tree /dev/null)
    fi

    echo $(git diff --cached $against --name-only | sed 's| |\\ |g')
}

formatFiles() {
    echo "$@" |
        cat |
        xargs |
        sed -e 's/ /,/g' |
        xargs dotnet format --include
}

stageFiles() {
    echo "$@" | xargs git add
}

main
